name: CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. pnpm 설치
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.2

      # 3. Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: "pnpm"

      # 4. 의존성 설치
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5. 파일 업로드
      - name: Upload project files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          rm: true
          source: .
          target: /home/${{ secrets.LIGHTSAIL_USERNAME }}/myworld
          strip_components: 1

      # 6. 서버 배포
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /home/${{ secrets.LIGHTSAIL_USERNAME }}/myworld

            command -v pnpm >/dev/null 2>&1 || npm install -g pnpm

            pnpm install --frozen-lockfile
            pnpm build

            pm2 describe myworld > /dev/null 2>&1
            if [ $? -eq 0 ]; then
              pm2 restart myworld
            else
              pm2 start pnpm --name myworld -- start
            fi

            pm2 save